---
title: "Claims level table"
author: "Spiro Stilianoudakis"
date: "9/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(openxlsx)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(sas7bdat)
library(lubridate)
library(tidyr)
library(tableone)
library(reshape2)
library(tidyr)
```

# Set working directory

```{r}
setwd("X:/CommonPrograms/Oral Health Services Research Core/Spiro/Claims_Project/data")
```

# Reading in unique claims

```{r}
unique_claims <- readRDS("X:/CommonPrograms/Oral Health Services Research Core/Spiro/Claims_Project/data/unique_claims.rds")
```

# Claims level table (mutually exclusive)

```{r}
claim_level <- unique_claims[order(unique_claims$CLAIM_NUMBER, decreasing = TRUE),]
```

## All years

```{r}
#total number
dim(claim_level)

#cdt category
table(claim_level$CDT_category, exclude = "ifany")
round(prop.table(table(claim_level$CDT_category, exclude = "ifany")), 3)
```

## 2015

```{r}
claim_level_2015 <- claim_level[which(claim_level$FY=="2015"),]
 
#total number
dim(claim_level_2015)

#cdt category
table(claim_level_2015$CDT_category, exclude = "ifany")
round(prop.table(table(claim_level_2015$CDT_category, exclude = "ifany")), 3)

```

## 2016

```{r}
claim_level_2016 <- claim_level[which(claim_level$FY=="2016"),]
 
#total number
dim(claim_level_2016)

#cdt category
table(claim_level_2016$CDT_category, exclude = "ifany")
round(prop.table(table(claim_level_2016$CDT_category, exclude = "ifany")), 3)

```

## 2017

```{r}
claim_level_2017 <- claim_level[which(claim_level$FY=="2017"),]
 
#total number
dim(claim_level_2017)

#cdt category
table(claim_level_2017$CDT_category, exclude = "ifany")
round(prop.table(table(claim_level_2017$CDT_category, exclude = "ifany")), 3)

```

## 2018

```{r}
claim_level_2018 <- claim_level[which(claim_level$FY=="2018"),]
 
#total number
dim(claim_level_2018)

#cdt category
table(claim_level_2018$CDT_category, exclude = "ifany")
round(prop.table(table(claim_level_2018$CDT_category, exclude = "ifany")), 3)

```

# Making table

```{r}
cbind.data.frame( #all years
				   AY=rbind(nrow(claim_level),
				   t(t(paste0(table(claim_level$CDT_category), " ", "(",round(prop.table(table(claim_level$CDT_category)), 3)*100, ")")))),
				   
				  #2015
				   FY2015=rbind(nrow(claim_level_2015),
				   t(t(paste0(table(claim_level_2015$CDT_category), " ", "(",round(prop.table(table(claim_level_2015$CDT_category)), 3)*100, ")")))),
				   
				  #2016
				   FY2016=rbind(nrow(claim_level_2016),
				   t(t(paste0(table(claim_level_2016$CDT_category), " ", "(",round(prop.table(table(claim_level_2016$CDT_category)), 3)*100, ")")))),
				   
				  #2017
				   FY2017=rbind(nrow(claim_level_2017),
				   t(t(paste0(table(claim_level_2017$CDT_category), " ", "(",round(prop.table(table(claim_level_2017$CDT_category)), 3)*100, ")")))),
				   
				  #2018
				   FY2018=rbind(nrow(claim_level_2018),
				   t(t(paste0(table(claim_level_2018$CDT_category), " ", "(",round(prop.table(table(claim_level_2018$CDT_category)), 3)*100, ")"))))
				 )
```

# Stacked barplot

```{r}
Year <- c(rep("2015", 7),
          rep("2016", 7),
          rep("2017", 7),
          rep("2018", 7))
Claim_Type <- rep(c("Preventative",
                    "Diagnostic",
                    "Restorative",
                    "Periodontics",
                    "Endodontics",
                    "Oral & Maxillofacial Surgery",
                    "Other"), 4)
Value <- c(as.vector(table(claim_level_2015$CDT_category)),
           as.vector(table(claim_level_2016$CDT_category)),
           as.vector(table(claim_level_2017$CDT_category)),
           as.vector(table(claim_level_2018$CDT_category)))

data <- cbind.data.frame(Year, Claim_Type, Value)
data$Claim_Type <- factor(data$Claim_Type, levels=c("Preventative",
                                                       "Diagnostic",
                                                       "Restorative",
                                                       "Periodontics",
                                                       "Endodontics",
                                                       "Oral & Maxillofacial Surgery",
                                                       "Other"))

ggplot(data, aes(fill=Claim_Type, y=Value, x=Year)) + 
  geom_bar(position="fill", stat="identity") +
  ylab("Percent") +
  scale_fill_discrete(name="Claim Type")+
  theme_bw() +
  #coord_flip() +
  theme(axis.text.x = element_text(size=15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        strip.text.x = element_text(size = 15),
        panel.spacing = unit(2, "lines"),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20))
  
spread(data, Year, Value)  
```

