---
title: "Investigating Months Enrolled"
author: "Spiro Stilianoudakis"
date: "1/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(openxlsx)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(sas7bdat)
library(lubridate)
```

# Set working directory

```{r}
setwd("X:/CommonPrograms/Oral Health Services Research Core/Spiro/Claims_Project/data")
```

# Read in full eligibility data (not filtered according to months enrolled > 3 months)

```{r}
eligibility <- readRDS("X:/CommonPrograms/Oral Health Services Research Core/Spiro/Claims_Project/data/ffs_mco_2015_2016_2017_2018_full.rds")

dim(eligibility) 
#103985    151

length(unique(eligibility$srecip)) 
#103985

eligibility <- eligibility[order(eligibility$srecip),]
```

#Calculating months enrolled 

##using only MCO

```{r}
#months enrolled
medata_mco <- eligibility[,grep(paste0(c("mco_beg1_2015",
                                                    "mco_beg2_2015",
                                                    "mco_beg3_2015",
                                                    "mco_beg4_2015",
                                                    "mco_end1_2015",
                                                    "mco_end2_2015",
                                                    "mco_end3_2015",
                                                    "mco_end4_2015",
                                                    
                                                    "mco_beg1_2016",
                                                    "mco_beg2_2016",
                                                    "mco_beg3_2016",
                                                    "mco_beg4_2016",
                                                    "mco_end1_2016",
                                                    "mco_end2_2016",
                                                    "mco_end3_2016",
                                                    "mco_end4_2016",
                                                    
                                                    "mco_beg1_2017",
                                                    "mco_beg2_2017",
                                                    "mco_beg3_2017",
                                                    "mco_beg4_2017",
                                                    "mco_end1_2017",
                                                    "mco_end2_2017",
                                                    "mco_end3_2017",
                                                    "mco_end4_2017",
                                                    
                                                    "mco_beg1_2018",
                                                    "mco_beg2_2018",
                                                    "mco_beg3_2018",
                                                    "mco_beg4_2018",
                                                    "mco_end1_2018",
                                                    "mco_end2_2018",
                                                    "mco_end3_2018",
                                                    "mco_end4_2018"),
                                   collapse = "|"), names(eligibility))]

myfunc_me <- function(x){
  df <- data.frame(matrix(t(x),nrow = 16,ncol=2, byrow = T))
  df2 <- df[order(df$X1, decreasing = FALSE),]
  df3 <- df2[order(df2$X2, decreasing = TRUE),]
  df4 <- df3[!duplicated(df3$X1),]
  df5 <- df4[!duplicated(df4$X2),]
  df6 <- na.omit(df5)
  #df7 <- df6 %>%
  #  arrange(X1) %>% 
  #  mutate(indx = c(0, cumsum(as.numeric(lead(X1)) >
  #                                cummax(as.numeric(X2)))[-n()])) %>%
  #  summarise(start = first(X1), end = last(X2))
  #me <- floor(as.numeric(sum(as.Date(df7$end)-as.Date(df7$start)))/30)
  me <- floor(as.numeric(sum(as.Date(df6$X2)-as.Date(df6$X1)))/30)
  return(me)
}

medata_mco$me <- apply(medata_mco, 1, myfunc_me)

eligibility$months_enrolled_mco <- medata_mco$me
summary(eligibility$months_enrolled_mco)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  0.000   3.000   7.000   7.013  10.000  48.000 

length(which(eligibility$months_enrolled_mco==0))
#22661
```

## using only FFS

```{r}
#months enrolled
medata_ffs <- eligibility[,grep(paste0(c("ffs_beg1_2015",
                                                    "ffs_beg2_2015",
                                                    "ffs_beg3_2015",
                                                    "ffs_beg4_2015",
                                                    "ffs_end1_2015",
                                                    "ffs_end2_2015",
                                                    "ffs_end3_2015",
                                                    "ffs_end4_2015",
                                                  
                                                    "ffs_beg1_2016",
                                                    "ffs_beg2_2016",
                                                    "ffs_beg3_2016",
                                                    "ffs_beg4_2016",
                                                    "ffs_end1_2016",
                                                    "ffs_end2_2016",
                                                    "ffs_end3_2016",
                                                    "ffs_end4_2016",
                                                    
                                                    "ffs_beg1_2017",
                                                    "ffs_beg2_2017",
                                                    "ffs_beg3_2017",
                                                    "ffs_beg4_2017",
                                                    "ffs_end1_2017",
                                                    "ffs_end2_2017",
                                                    "ffs_end3_2017",
                                                    "ffs_end4_2017",
                                                    
                                                    "ffs_beg1_2018",
                                                    "ffs_beg2_2018",
                                                    "ffs_beg3_2018",
                                                    "ffs_beg4_2018",
                                                    "ffs_end1_2018",
                                                    "ffs_end2_2018",
                                                    "ffs_end3_2018",
                                                    "ffs_end4_2018"),
                                   collapse = "|"), names(eligibility))]

medata_ffs$me <- apply(medata_ffs, 1, myfunc_me)

eligibility$months_enrolled_ffs <- medata_ffs$me
summary(eligibility$months_enrolled_ffs)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   0.00    8.00   12.00   12.36   16.00   48.00 

length(which(eligibility$months_enrolled_ffs==0))
#128
```

##Filling in 0 months enrolled for mco with ffs months enrolled

```{r}
length(intersect(eligibility$srecip[which(eligibility$months_enrolled_mco==0)],eligibility$srecip[which(eligibility$months_enrolled_ffs==0)]))
#0

eligibility$months_enrolled <- eligibility$months_enrolled_ffs
eligibility$months_enrolled[which(eligibility$months_enrolled_ffs==0)] <- eligibility$months_enrolled_mco[which(eligibility$months_enrolled_ffs==0)]

summary(eligibility$months_enrolled)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#   2.00    8.00   12.00   12.36   16.00   48.00 

length(which(eligibility$months_enrolled<3))
#306

hist(eligibility$months_enrolled)
```

# Calculating gap days

## using MCO

```{r}
gapdays_mco <- eligibility[,grep(paste0(c("mco_beg1_2015",
                                                    "mco_beg2_2015",
                                                    "mco_beg3_2015",
                                                    "mco_beg4_2015",
                                                    "mco_end1_2015",
                                                    "mco_end2_2015",
                                                    "mco_end3_2015",
                                                    "mco_end4_2015",
                                                    
                                                    "mco_beg1_2016",
                                                    "mco_beg2_2016",
                                                    "mco_beg3_2016",
                                                    "mco_beg4_2016",
                                                    "mco_end1_2016",
                                                    "mco_end2_2016",
                                                    "mco_end3_2016",
                                                    "mco_end4_2016",
                                                    
                                                    "mco_beg1_2017",
                                                    "mco_beg2_2017",
                                                    "mco_beg3_2017",
                                                    "mco_beg4_2017",
                                                    "mco_end1_2017",
                                                    "mco_end2_2017",
                                                    "mco_end3_2017",
                                                    "mco_end4_2017",
                                                    
                                                    "mco_beg1_2018",
                                                    "mco_beg2_2018",
                                                    "mco_beg3_2018",
                                                    "mco_beg4_2018",
                                                    "mco_end1_2018",
                                                    "mco_end2_2018",
                                                    "mco_end3_2018",
                                                    "mco_end4_2018"),
                                   collapse = "|"), names(eligibility))]

myfunc_gp <- function(x){
  df <- data.frame(matrix(t(x),nrow = 16,ncol=2, byrow = T))
  df2 <- df[order(df$X1, decreasing = FALSE),]
  df3 <- df2[order(df2$X2, decreasing = FALSE),]
  df4 <- df3[!duplicated(df3$X1),]
  df5 <- df4[!duplicated(df4$X2),]
  df6 <- na.omit(df5)
  if(nrow(df6)==0){
    gp=NA
  }else{
    df6$lagX1 <- c(as.character(df6$X1[-1]),NA)
    gp <- sum(as.vector(as.Date(df6$lagX1)-as.Date(df6$X2)-1), na.rm = TRUE) #subtract 1 so as to remove gaps days between fiscal years
  }
  return(gp)
}

gapdays_mco$gp <- apply(gapdays_mco, 1, myfunc_gp)

eligibility$gapdays_mco <- gapdays_mco$gp
summary(eligibility$gapdays_mco)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#   0.00    0.00    0.00   52.34    0.00 1278.00   22661 
hist(eligibility$gapdays_mco)
```

## using ffs

```{r}
gapdays_ffs <- eligibility[,grep(paste0(c("ffs_beg1_2015",
                                                    "ffs_beg2_2015",
                                                    "ffs_beg3_2015",
                                                    "ffs_beg4_2015",
                                                    "ffs_end1_2015",
                                                    "ffs_end2_2015",
                                                    "ffs_end3_2015",
                                                    "ffs_end4_2015",
                                                  
                                                    "ffs_beg1_2016",
                                                    "ffs_beg2_2016",
                                                    "ffs_beg3_2016",
                                                    "ffs_beg4_2016",
                                                    "ffs_end1_2016",
                                                    "ffs_end2_2016",
                                                    "ffs_end3_2016",
                                                    "ffs_end4_2016",
                                                    
                                                    "ffs_beg1_2017",
                                                    "ffs_beg2_2017",
                                                    "ffs_beg3_2017",
                                                    "ffs_beg4_2017",
                                                    "ffs_end1_2017",
                                                    "ffs_end2_2017",
                                                    "ffs_end3_2017",
                                                    "ffs_end4_2017",
                                                    
                                                    "ffs_beg1_2018",
                                                    "ffs_beg2_2018",
                                                    "ffs_beg3_2018",
                                                    "ffs_beg4_2018",
                                                    "ffs_end1_2018",
                                                    "ffs_end2_2018",
                                                    "ffs_end3_2018",
                                                    "ffs_end4_2018"),
                                   collapse = "|"), names(eligibility))]

gapdays_ffs$gp <- apply(gapdays_ffs, 1, myfunc_gp)

eligibility$gapdays_ffs <- gapdays_ffs$gp
summary(eligibility$gapdays_ffs)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#   0.00    0.00    0.00   46.36    0.00 1278.00     128 
hist(eligibility$gapdays_ffs)
```

# Calculating separate number of times enrolled

##using mco

```{r}
numtimes_mco <- eligibility[,grep(paste0(c("mco_beg1_2015",
                                                    "mco_beg2_2015",
                                                    "mco_beg3_2015",
                                                    "mco_beg4_2015",
                                                    "mco_end1_2015",
                                                    "mco_end2_2015",
                                                    "mco_end3_2015",
                                                    "mco_end4_2015",
                                                    
                                                    "mco_beg1_2016",
                                                    "mco_beg2_2016",
                                                    "mco_beg3_2016",
                                                    "mco_beg4_2016",
                                                    "mco_end1_2016",
                                                    "mco_end2_2016",
                                                    "mco_end3_2016",
                                                    "mco_end4_2016",
                                                    
                                                    "mco_beg1_2017",
                                                    "mco_beg2_2017",
                                                    "mco_beg3_2017",
                                                    "mco_beg4_2017",
                                                    "mco_end1_2017",
                                                    "mco_end2_2017",
                                                    "mco_end3_2017",
                                                    "mco_end4_2017",
                                                    
                                                    "mco_beg1_2018",
                                                    "mco_beg2_2018",
                                                    "mco_beg3_2018",
                                                    "mco_beg4_2018",
                                                    "mco_end1_2018",
                                                    "mco_end2_2018",
                                                    "mco_end3_2018",
                                                    "mco_end4_2018"),
                                   collapse = "|"), names(eligibility))]

myfunc_nt <- function(x){
  df <- data.frame(matrix(t(x),nrow = 16,ncol=2, byrow = T))
  df2 <- df[order(df$X1, decreasing = FALSE),]
  df3 <- df2[order(df2$X2, decreasing = FALSE),]
  df4 <- df3[!duplicated(df3$X1),]
  df5 <- df4[!duplicated(df4$X2),]
  df6 <- na.omit(df5)
  nt <- nrow(df6)
  return(nt)
}

numtimes_mco$nt <- apply(numtimes_mco, 1, myfunc_nt)

eligibility$numtimes_mco <- numtimes_mco$nt
summary(eligibility$numtimes_mco)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  0.000   1.000   1.000   1.183   2.000   7.000 
  
hist(eligibility$numtimes_mco)
```

##using ffs

```{r}
numtimes_ffs <- eligibility[,grep(paste0(c("ffs_beg1_2015",
                                                    "ffs_beg2_2015",
                                                    "ffs_beg3_2015",
                                                    "ffs_beg4_2015",
                                                    "ffs_end1_2015",
                                                    "ffs_end2_2015",
                                                    "ffs_end3_2015",
                                                    "ffs_end4_2015",
                                                  
                                                    "ffs_beg1_2016",
                                                    "ffs_beg2_2016",
                                                    "ffs_beg3_2016",
                                                    "ffs_beg4_2016",
                                                    "ffs_end1_2016",
                                                    "ffs_end2_2016",
                                                    "ffs_end3_2016",
                                                    "ffs_end4_2016",
                                                    
                                                    "ffs_beg1_2017",
                                                    "ffs_beg2_2017",
                                                    "ffs_beg3_2017",
                                                    "ffs_beg4_2017",
                                                    "ffs_end1_2017",
                                                    "ffs_end2_2017",
                                                    "ffs_end3_2017",
                                                    "ffs_end4_2017",
                                                    
                                                    "ffs_beg1_2018",
                                                    "ffs_beg2_2018",
                                                    "ffs_beg3_2018",
                                                    "ffs_beg4_2018",
                                                    "ffs_end1_2018",
                                                    "ffs_end2_2018",
                                                    "ffs_end3_2018",
                                                    "ffs_end4_2018"),
                                   collapse = "|"), names(eligibility))]

numtimes_ffs$nt <- apply(numtimes_ffs, 1, myfunc_nt)

eligibility$numtimes_ffs <- numtimes_ffs$nt
summary(eligibility$numtimes_ffs)
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#  0.000   1.000   1.000   1.578   2.000   7.000 
  
hist(eligibility$numtimes_ffs)
```

