---
title: "Patient level claims table"
author: "Spiro Stilianoudakis"
date: "9/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(openxlsx)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(sas7bdat)
library(lubridate)
library(tidyr)
library(tableone)
```

# Set working directory

```{r}
setwd("X:/CommonPrograms/Oral Health Services Research Core/Spiro/Claims_Project/data")
```

# Reading in unique claims

```{r}
unique_claims <- readRDS("X:/CommonPrograms/Oral Health Services Research Core/Spiro/Claims_Project/data/unique_claims.rds")
```

<!--
# Reading in eligibility

```{r}
eligibility <- readRDS("X:/CommonPrograms/Oral Health Services Research Core/Spiro/Claims_Project/data/ffs_mco_2015_2016_2017_2018.rds")

dim(eligibility) #103204    156
length(unique(eligibility$srecip)) #103204

```
-->

# Determining the frequency of different fiscal years each subject had a claim in

```{r}
d <- unique_claims %>% group_by(SRECIP) %>% summarize(x = length(unique(FY)))
table(d$x)
#    1     2     3     4 
#14094  2641   151     5 

d$SRECIP[which(d$x==4)]
#"312400495901" "354416003605" "361801135801" "393637009402" "605557201003"

unique_claims[which(unique_claims$SRECIP=="312400495901"),]
```

<!--
# Recoding Race

```{r}
unique_claims$Overall_Race[which(unique_claims$Overall_Race=="Hispanic" |
                             unique_claims$Overall_Race=="Native American/Asian" |
                             unique_claims$Overall_Race=="Other")] <- "Other"

table(unique_claims$Overall_Race)

```
-->

# Patient level table using claims data (not mutually exclusive)

## All years

```{r}
patient_level <- unique_claims[!duplicated(unique_claims$SRECIP),]

#total
dim(patient_level)

#number of claims
num_claims <- unique_claims %>%
  group_by(SRECIP) %>%
  count()
mean(num_claims$n)
sd(num_claims$n)

#number of visits
num_visits <- unique_claims %>%
  group_by(SRECIP) %>%
  summarize(n = length(unique(SERVICE_DATE)))
mean(num_visits$n)
sd(num_visits$n)

#number of services
num_service <- unique_claims %>%
    group_by(SRECIP) %>%
    summarize(n = length(unique(CDT_category)))
mean(num_service$n)
sd(num_service$n)

#number of DIAGNOSTIC services
num_DIAGNOSTIC <- unique_claims %>%
    filter(CDT_category=="DIAGNOSTIC") %>%
    group_by(SRECIP) %>%
    count()
mean(num_DIAGNOSTIC$n)
sd(num_DIAGNOSTIC$n)

#number of PREVENTIVE services
num_PREVENTIVE <- unique_claims %>%
    filter(CDT_category=="PREVENTIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PREVENTIVE$n)
sd(num_PREVENTIVE$n)

#number of RESTORATIVE services
num_RESTORATIVE <- unique_claims %>%
    filter(CDT_category=="RESTORATIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_RESTORATIVE$n)
sd(num_RESTORATIVE$n)

#number of PERIODONTICS services
num_PERIODONTICS <- unique_claims %>%
    filter(CDT_category=="PERIODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PERIODONTICS$n)
sd(num_PERIODONTICS$n)

#number of PROSTHODONTICS services
num_PROSTHODONTICS <- unique_claims %>%
    filter(CDT_category=="PROSTHODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PROSTHODONTICS$n)
sd(num_PROSTHODONTICS$n)

#number of ENDODONTICS services
num_ENDODONTICS <- unique_claims %>%
    filter(CDT_category=="ENDODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ENDODONTICS$n)
sd(num_ENDODONTICS$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ORAL_MAXILLOFACIAL_SURGERY <- unique_claims %>%
    filter(CDT_category=="ORAL & MAXILLOFACIAL SURGERY") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ORAL_MAXILLOFACIAL_SURGERY$n)
sd(num_ORAL_MAXILLOFACIAL_SURGERY$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ADJUNCTIVE_GENERAL_SERVICES <- unique_claims %>%
    filter(CDT_category=="ADJUNCTIVE GENERAL SERVICES") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ADJUNCTIVE_GENERAL_SERVICES$n)
sd(num_ADJUNCTIVE_GENERAL_SERVICES$n)

#age
mean(patient_level$Overall_Age_at_earliest_enrollment)
sd(patient_level$Overall_Age_at_earliest_enrollment)

#age category
table(patient_level$age_cat_eligibility)
round(prop.table(table(patient_level$age_cat_eligibility)), 3)

#race
table(patient_level$Overall_Race)
round(prop.table(table(patient_level$Overall_Race)), 3)

#citizenship
table(patient_level$Overall_Citizen)
round(prop.table(table(patient_level$Overall_Citizen)), 3)

#hpsa
table(patient_level$HPSA_status)
round(prop.table(table(patient_level$HPSA_status)), 3)

#region
table(patient_level$Overall_Region)
round(prop.table(table(patient_level$Overall_Region)), 3)

#hpd
table(patient_level$HEALTH_PLANNING_DISTRICT)
round(prop.table(table(patient_level$HEALTH_PLANNING_DISTRICT)), 3)

#hpr
table(patient_level$HEALTH_PLANNING_REGION)
round(prop.table(table(patient_level$HEALTH_PLANNING_REGION)), 3)

#CDT category
##PREVENTIVE
patient_level$PREVENTIVE <- as.vector(sapply(patient_level$SRECIP, function(x){ifelse("PREVENTIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level$PREVENTIVE)
prop.table(table(patient_level$PREVENTIVE))

##DIAGNOSTIC
patient_level$DIAGNOSTIC <- as.vector(sapply(patient_level$SRECIP, function(x){ifelse("DIAGNOSTIC" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level$DIAGNOSTIC)
prop.table(table(patient_level$DIAGNOSTIC))

##RESTORATIVE
patient_level$RESTORATIVE <- as.vector(sapply(patient_level$SRECIP, function(x){ifelse("RESTORATIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level$RESTORATIVE)
prop.table(table(patient_level$RESTORATIVE))

##PERIODONTICS
patient_level$PERIODONTICS <- as.vector(sapply(patient_level$SRECIP, function(x){ifelse("PERIODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level$PERIODONTICS)
prop.table(table(patient_level$PERIODONTICS))

##ENDODONTICS
patient_level$ENDODONTICS <- as.vector(sapply(patient_level$SRECIP, function(x){ifelse("ENDODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level$ENDODONTICS)
prop.table(table(patient_level$ENDODONTICS))

##ORAL & MAXILLOFACIAL SURGERY
patient_level$ORAL_and_MAXILLOFACIAL_SURGERY <- as.vector(sapply(patient_level$SRECIP, function(x){ifelse("ORAL & MAXILLOFACIAL SURGERY" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level$ORAL_and_MAXILLOFACIAL_SURGERY)
prop.table(table(patient_level$ORAL_and_MAXILLOFACIAL_SURGERY))

##OTHER
patient_level$OTHER <- as.vector(sapply(patient_level$SRECIP, function(x){ifelse("OTHER" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level$OTHER)
prop.table(table(patient_level$OTHER))

```

## 2015

```{r}
patient_level_2015 <- unique_claims[which(unique_claims$FY=="2015"),]
patient_level_2015 <- patient_level_2015[!duplicated(patient_level_2015$SRECIP),]

#total
dim(patient_level_2015)

#number of claims
num_claims_2015 <- unique_claims %>%
  filter(FY=="2015") %>%
  group_by(SRECIP) %>%
  count()
mean(num_claims_2015$n)
sd(num_claims_2015$n)

#number of visits
num_visits_2015 <- unique_claims %>%
  filter(FY=="2015") %>%
  group_by(SRECIP) %>%
  summarize(n = length(unique(SERVICE_DATE)))
mean(num_visits_2015$n)
sd(num_visits_2015$n)

#number of services
num_service_2015 <- unique_claims %>%
    filter(FY=="2015") %>%
    group_by(SRECIP) %>%
    summarize(n = length(unique(CDT_category)))
mean(num_service_2015$n)
sd(num_service_2015$n)

#number of DIAGNOSTIC services
num_DIAGNOSTIC <- unique_claims %>%
    filter(FY=="2015", CDT_category=="DIAGNOSTIC") %>%
    group_by(SRECIP) %>%
    count()
mean(num_DIAGNOSTIC$n)
sd(num_DIAGNOSTIC$n)

#number of PREVENTIVE services
num_PREVENTIVE <- unique_claims %>%
    filter(FY=="2015", CDT_category=="PREVENTIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PREVENTIVE$n)
sd(num_PREVENTIVE$n)

#number of RESTORATIVE services
num_RESTORATIVE <- unique_claims %>%
    filter(FY=="2015", CDT_category=="RESTORATIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_RESTORATIVE$n)
sd(num_RESTORATIVE$n)

#number of PERIODONTICS services
num_PERIODONTICS <- unique_claims %>%
    filter(FY=="2015", CDT_category=="PERIODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PERIODONTICS$n)
sd(num_PERIODONTICS$n)

#number of PROSTHODONTICS services
num_PROSTHODONTICS <- unique_claims %>%
    filter(FY=="2015", CDT_category=="PROSTHODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PROSTHODONTICS$n)
sd(num_PROSTHODONTICS$n)

#number of ENDODONTICS services
num_ENDODONTICS <- unique_claims %>%
    filter(FY=="2015", CDT_category=="ENDODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ENDODONTICS$n)
sd(num_ENDODONTICS$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ORAL_MAXILLOFACIAL_SURGERY <- unique_claims %>%
    filter(FY=="2015", CDT_category=="ORAL & MAXILLOFACIAL SURGERY") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ORAL_MAXILLOFACIAL_SURGERY$n)
sd(num_ORAL_MAXILLOFACIAL_SURGERY$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ADJUNCTIVE_GENERAL_SERVICES <- unique_claims %>%
    filter(FY=="2015", CDT_category=="ADJUNCTIVE GENERAL SERVICES") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ADJUNCTIVE_GENERAL_SERVICES$n)
sd(num_ADJUNCTIVE_GENERAL_SERVICES$n)


#age
mean(patient_level_2015$Overall_Age_at_earliest_enrollment)
sd(patient_level_2015$Overall_Age_at_earliest_enrollment)

#age category
table(patient_level_2015$age_cat_eligibility)
round(prop.table(table(patient_level_2015$age_cat_eligibility)), 3)

#race
table(patient_level_2015$Overall_Race)
round(prop.table(table(patient_level_2015$Overall_Race)), 3)

#citizenship
table(patient_level_2015$Overall_Citizen)
round(prop.table(table(patient_level_2015$Overall_Citizen)), 3)

#hpsa
table(patient_level_2015$HPSA_status)
round(prop.table(table(patient_level_2015$HPSA_status)), 3)

#region
table(patient_level_2015$Overall_Region)
round(prop.table(table(patient_level_2015$Overall_Region)), 3)

#hpd
table(patient_level_2015$HEALTH_PLANNING_DISTRICT)
round(prop.table(table(patient_level_2015$HEALTH_PLANNING_DISTRICT)), 3)

#hpr
table(patient_level_2015$HEALTH_PLANNING_REGION)
round(prop.table(table(patient_level_2015$HEALTH_PLANNING_REGION)), 3)

#CDT category
##PREVENTIVE
patient_level_2015$PREVENTIVE <- as.vector(sapply(patient_level_2015$SRECIP, function(x){ifelse("PREVENTIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2015$PREVENTIVE)
prop.table(table(patient_level_2015$PREVENTIVE))

##DIAGNOSTIC
patient_level_2015$DIAGNOSTIC <- as.vector(sapply(patient_level_2015$SRECIP, function(x){ifelse("DIAGNOSTIC" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2015$DIAGNOSTIC)
prop.table(table(patient_level_2015$DIAGNOSTIC))

##RESTORATIVE
patient_level_2015$RESTORATIVE <- as.vector(sapply(patient_level_2015$SRECIP, function(x){ifelse("RESTORATIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2015$RESTORATIVE)
prop.table(table(patient_level_2015$RESTORATIVE))

##PERIODONTICS
patient_level_2015$PERIODONTICS <- as.vector(sapply(patient_level_2015$SRECIP, function(x){ifelse("PERIODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2015$PERIODONTICS)
prop.table(table(patient_level_2015$PERIODONTICS))

##ENDODONTICS
patient_level_2015$ENDODONTICS <- as.vector(sapply(patient_level_2015$SRECIP, function(x){ifelse("ENDODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2015$ENDODONTICS)
prop.table(table(patient_level_2015$ENDODONTICS))

##ORAL & MAXILLOFACIAL SURGERY
patient_level_2015$ORAL_and_MAXILLOFACIAL_SURGERY <- as.vector(sapply(patient_level_2015$SRECIP, function(x){ifelse("ORAL & MAXILLOFACIAL SURGERY" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2015$ORAL_and_MAXILLOFACIAL_SURGERY)
prop.table(table(patient_level_2015$ORAL_and_MAXILLOFACIAL_SURGERY))

##OTHER
patient_level_2015$OTHER <- as.vector(sapply(patient_level_2015$SRECIP, function(x){ifelse("OTHER" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2015$OTHER)
prop.table(table(patient_level_2015$OTHER))
```

## 2016

```{r}
patient_level_2016 <- unique_claims[which(unique_claims$FY=="2016"),]
patient_level_2016 <- patient_level_2016[!duplicated(patient_level_2016$SRECIP),]

#total
dim(patient_level_2016)

#number of claims
num_claims_2016 <- unique_claims %>%
  filter(FY=="2016") %>%
  group_by(SRECIP) %>%
  count()
mean(num_claims_2016$n)
sd(num_claims_2016$n)

#number of visits
num_visits_2016 <- unique_claims %>%
  filter(FY=="2016") %>%
  group_by(SRECIP) %>%
  summarize(n = length(unique(SERVICE_DATE)))
mean(num_visits_2016$n)
sd(num_visits_2016$n)

#number of services
num_service_2016 <- unique_claims %>%
    filter(FY=="2016") %>%
    group_by(SRECIP) %>%
    summarize(n = length(unique(CDT_category)))
mean(num_service_2016$n)
sd(num_service_2016$n)

#number of DIAGNOSTIC services
num_DIAGNOSTIC <- unique_claims %>%
    filter(FY=="2016", CDT_category=="DIAGNOSTIC") %>%
    group_by(SRECIP) %>%
    count()
mean(num_DIAGNOSTIC$n)
sd(num_DIAGNOSTIC$n)

#number of PREVENTIVE services
num_PREVENTIVE <- unique_claims %>%
    filter(FY=="2016", CDT_category=="PREVENTIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PREVENTIVE$n)
sd(num_PREVENTIVE$n)

#number of RESTORATIVE services
num_RESTORATIVE <- unique_claims %>%
    filter(FY=="2016", CDT_category=="RESTORATIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_RESTORATIVE$n)
sd(num_RESTORATIVE$n)

#number of PERIODONTICS services
num_PERIODONTICS <- unique_claims %>%
    filter(FY=="2016", CDT_category=="PERIODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PERIODONTICS$n)
sd(num_PERIODONTICS$n)

#number of PROSTHODONTICS services
num_PROSTHODONTICS <- unique_claims %>%
    filter(FY=="2016", CDT_category=="PROSTHODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PROSTHODONTICS$n)
sd(num_PROSTHODONTICS$n)

#number of ENDODONTICS services
num_ENDODONTICS <- unique_claims %>%
    filter(FY=="2016", CDT_category=="ENDODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ENDODONTICS$n)
sd(num_ENDODONTICS$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ORAL_MAXILLOFACIAL_SURGERY <- unique_claims %>%
    filter(FY=="2016", CDT_category=="ORAL & MAXILLOFACIAL SURGERY") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ORAL_MAXILLOFACIAL_SURGERY$n)
sd(num_ORAL_MAXILLOFACIAL_SURGERY$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ADJUNCTIVE_GENERAL_SERVICES <- unique_claims %>%
    filter(FY=="2016", CDT_category=="ADJUNCTIVE GENERAL SERVICES") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ADJUNCTIVE_GENERAL_SERVICES$n)
sd(num_ADJUNCTIVE_GENERAL_SERVICES$n)

#age
mean(patient_level_2016$Overall_Age_at_earliest_enrollment)
sd(patient_level_2016$Overall_Age_at_earliest_enrollment)

#age category
table(patient_level_2016$age_cat_eligibility)
round(prop.table(table(patient_level_2016$age_cat_eligibility)), 3)

#race
table(patient_level_2016$Overall_Race)
round(prop.table(table(patient_level_2016$Overall_Race)), 3)

#citizenship
table(patient_level_2016$Overall_Citizen)
round(prop.table(table(patient_level_2016$Overall_Citizen)), 3)

#hpsa
table(patient_level_2016$HPSA_status)
round(prop.table(table(patient_level_2016$HPSA_status)), 3)

#region
table(patient_level_2016$Overall_Region)
round(prop.table(table(patient_level_2016$Overall_Region)), 3)

#hpd
table(patient_level_2016$HEALTH_PLANNING_DISTRICT)
round(prop.table(table(patient_level_2016$HEALTH_PLANNING_DISTRICT)), 3)

#hpr
table(patient_level_2016$HEALTH_PLANNING_REGION)
round(prop.table(table(patient_level_2016$HEALTH_PLANNING_REGION)), 3)

#CDT category
##PREVENTIVE
patient_level_2016$PREVENTIVE <- as.vector(sapply(patient_level_2016$SRECIP, function(x){ifelse("PREVENTIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2016$PREVENTIVE)
prop.table(table(patient_level_2016$PREVENTIVE))

##DIAGNOSTIC
patient_level_2016$DIAGNOSTIC <- as.vector(sapply(patient_level_2016$SRECIP, function(x){ifelse("DIAGNOSTIC" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2016$DIAGNOSTIC)
prop.table(table(patient_level_2016$DIAGNOSTIC))

##RESTORATIVE
patient_level_2016$RESTORATIVE <- as.vector(sapply(patient_level_2016$SRECIP, function(x){ifelse("RESTORATIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2016$RESTORATIVE)
prop.table(table(patient_level_2016$RESTORATIVE))

##PERIODONTICS
patient_level_2016$PERIODONTICS <- as.vector(sapply(patient_level_2016$SRECIP, function(x){ifelse("PERIODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2016$PERIODONTICS)
prop.table(table(patient_level_2016$PERIODONTICS))

##ENDODONTICS
patient_level_2016$ENDODONTICS <- as.vector(sapply(patient_level_2016$SRECIP, function(x){ifelse("ENDODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2016$ENDODONTICS)
prop.table(table(patient_level_2016$ENDODONTICS))

##ORAL & MAXILLOFACIAL SURGERY
patient_level_2016$ORAL_and_MAXILLOFACIAL_SURGERY <- as.vector(sapply(patient_level_2016$SRECIP, function(x){ifelse("ORAL & MAXILLOFACIAL SURGERY" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2016$ORAL_and_MAXILLOFACIAL_SURGERY)
prop.table(table(patient_level_2016$ORAL_and_MAXILLOFACIAL_SURGERY))

##OTHER
patient_level_2016$OTHER <- as.vector(sapply(patient_level_2016$SRECIP, function(x){ifelse("OTHER" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2016$OTHER)
prop.table(table(patient_level_2016$OTHER))
```

## 2017

```{r}
patient_level_2017 <- unique_claims[which(unique_claims$FY=="2017"),]
patient_level_2017 <- patient_level_2017[!duplicated(patient_level_2017$SRECIP),]

#total
dim(patient_level_2017)

#number of claims
num_claims_2017 <- unique_claims %>%
  filter(FY=="2017") %>%
  group_by(SRECIP) %>%
  count()
mean(num_claims_2017$n)
sd(num_claims_2017$n)

#number of visits
num_visits_2017 <- unique_claims %>%
  filter(FY=="2017") %>%
  group_by(SRECIP) %>%
  summarize(n = length(unique(SERVICE_DATE)))
mean(num_visits_2017$n)
sd(num_visits_2017$n)

#number of services
num_service_2017 <- unique_claims %>%
    filter(FY=="2017") %>%
    group_by(SRECIP) %>%
    summarize(n = length(unique(CDT_category)))
mean(num_service_2017$n)
sd(num_service_2017$n)

#number of DIAGNOSTIC services
num_DIAGNOSTIC <- unique_claims %>%
    filter(FY=="2017", CDT_category=="DIAGNOSTIC") %>%
    group_by(SRECIP) %>%
    count()
mean(num_DIAGNOSTIC$n)
sd(num_DIAGNOSTIC$n)

#number of PREVENTIVE services
num_PREVENTIVE <- unique_claims %>%
    filter(FY=="2017", CDT_category=="PREVENTIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PREVENTIVE$n)
sd(num_PREVENTIVE$n)

#number of RESTORATIVE services
num_RESTORATIVE <- unique_claims %>%
    filter(FY=="2017", CDT_category=="RESTORATIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_RESTORATIVE$n)
sd(num_RESTORATIVE$n)

#number of PERIODONTICS services
num_PERIODONTICS <- unique_claims %>%
    filter(FY=="2017", CDT_category=="PERIODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PERIODONTICS$n)
sd(num_PERIODONTICS$n)

#number of PROSTHODONTICS services
num_PROSTHODONTICS <- unique_claims %>%
    filter(FY=="2017", CDT_category=="PROSTHODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PROSTHODONTICS$n)
sd(num_PROSTHODONTICS$n)

#number of ENDODONTICS services
num_ENDODONTICS <- unique_claims %>%
    filter(FY=="2017", CDT_category=="ENDODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ENDODONTICS$n)
sd(num_ENDODONTICS$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ORAL_MAXILLOFACIAL_SURGERY <- unique_claims %>%
    filter(FY=="2017", CDT_category=="ORAL & MAXILLOFACIAL SURGERY") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ORAL_MAXILLOFACIAL_SURGERY$n)
sd(num_ORAL_MAXILLOFACIAL_SURGERY$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ADJUNCTIVE_GENERAL_SERVICES <- unique_claims %>%
    filter(FY=="2017", CDT_category=="ADJUNCTIVE GENERAL SERVICES") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ADJUNCTIVE_GENERAL_SERVICES$n)
sd(num_ADJUNCTIVE_GENERAL_SERVICES$n)

#age
mean(patient_level_2017$Overall_Age_at_earliest_enrollment)
sd(patient_level_2017$Overall_Age_at_earliest_enrollment)

#age category
table(patient_level_2017$age_cat_eligibility)
round(prop.table(table(patient_level_2017$age_cat_eligibility)), 3)

#race
table(patient_level_2017$Overall_Race)
round(prop.table(table(patient_level_2017$Overall_Race)), 3)

#citizenship
table(patient_level_2017$Overall_Citizen)
round(prop.table(table(patient_level_2017$Overall_Citizen)), 3)

#hpsa
table(patient_level_2017$HPSA_status)
round(prop.table(table(patient_level_2017$HPSA_status)), 3)

#region
table(patient_level_2017$Overall_Region)
round(prop.table(table(patient_level_2017$Overall_Region)), 3)

#hpd
table(patient_level_2017$HEALTH_PLANNING_DISTRICT)
round(prop.table(table(patient_level_2017$HEALTH_PLANNING_DISTRICT)), 3)

#hpr
table(patient_level_2017$HEALTH_PLANNING_REGION)
round(prop.table(table(patient_level_2017$HEALTH_PLANNING_REGION)), 3)

#CDT category
##PREVENTIVE
patient_level_2017$PREVENTIVE <- as.vector(sapply(patient_level_2017$SRECIP, function(x){ifelse("PREVENTIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2017$PREVENTIVE)
prop.table(table(patient_level_2017$PREVENTIVE))

##DIAGNOSTIC
patient_level_2017$DIAGNOSTIC <- as.vector(sapply(patient_level_2017$SRECIP, function(x){ifelse("DIAGNOSTIC" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2017$DIAGNOSTIC)
prop.table(table(patient_level_2017$DIAGNOSTIC))

##RESTORATIVE
patient_level_2017$RESTORATIVE <- as.vector(sapply(patient_level_2017$SRECIP, function(x){ifelse("RESTORATIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2017$RESTORATIVE)
prop.table(table(patient_level_2017$RESTORATIVE))

##PERIODONTICS
patient_level_2017$PERIODONTICS <- as.vector(sapply(patient_level_2017$SRECIP, function(x){ifelse("PERIODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2017$PERIODONTICS)
prop.table(table(patient_level_2017$PERIODONTICS))

##ENDODONTICS
patient_level_2017$ENDODONTICS <- as.vector(sapply(patient_level_2017$SRECIP, function(x){ifelse("ENDODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2017$ENDODONTICS)
prop.table(table(patient_level_2017$ENDODONTICS))

##ORAL & MAXILLOFACIAL SURGERY
patient_level_2017$ORAL_and_MAXILLOFACIAL_SURGERY <- as.vector(sapply(patient_level_2017$SRECIP, function(x){ifelse("ORAL & MAXILLOFACIAL SURGERY" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2017$ORAL_and_MAXILLOFACIAL_SURGERY)
prop.table(table(patient_level_2017$ORAL_and_MAXILLOFACIAL_SURGERY))

##OTHER
patient_level_2017$OTHER <- as.vector(sapply(patient_level_2017$SRECIP, function(x){ifelse("OTHER" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2017$OTHER)
prop.table(table(patient_level_2017$OTHER))
```

## 2018

```{r}
patient_level_2018 <- unique_claims[which(unique_claims$FY=="2018"),]
patient_level_2018 <- patient_level_2018[!duplicated(patient_level_2018$SRECIP),]

#total
dim(patient_level_2018)

#number of claims
num_claims_2018 <- unique_claims %>%
  filter(FY=="2018") %>%
  group_by(SRECIP) %>%
  count()
mean(num_claims_2018$n)
sd(num_claims_2018$n)

#number of visits
num_visits_2018 <- unique_claims %>%
  filter(FY=="2018") %>%
  group_by(SRECIP) %>%
  summarize(n = length(unique(SERVICE_DATE)))
mean(num_visits_2018$n)
sd(num_visits_2018$n)

#number of services
num_service_2018 <- unique_claims %>%
    filter(FY=="2018") %>%
    group_by(SRECIP) %>%
    summarize(n = length(unique(CDT_category)))
mean(num_service_2018$n)
sd(num_service_2018$n)

#number of DIAGNOSTIC services
num_DIAGNOSTIC <- unique_claims %>%
    filter(FY=="2018", CDT_category=="DIAGNOSTIC") %>%
    group_by(SRECIP) %>%
    count()
mean(num_DIAGNOSTIC$n)
sd(num_DIAGNOSTIC$n)

#number of PREVENTIVE services
num_PREVENTIVE <- unique_claims %>%
    filter(FY=="2018", CDT_category=="PREVENTIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PREVENTIVE$n)
sd(num_PREVENTIVE$n)

#number of RESTORATIVE services
num_RESTORATIVE <- unique_claims %>%
    filter(FY=="2018", CDT_category=="RESTORATIVE") %>%
    group_by(SRECIP) %>%
    count()
mean(num_RESTORATIVE$n)
sd(num_RESTORATIVE$n)

#number of PERIODONTICS services
num_PERIODONTICS <- unique_claims %>%
    filter(FY=="2018", CDT_category=="PERIODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PERIODONTICS$n)
sd(num_PERIODONTICS$n)

#number of PROSTHODONTICS services
num_PROSTHODONTICS <- unique_claims %>%
    filter(FY=="2018", CDT_category=="PROSTHODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_PROSTHODONTICS$n)
sd(num_PROSTHODONTICS$n)

#number of ENDODONTICS services
num_ENDODONTICS <- unique_claims %>%
    filter(FY=="2018", CDT_category=="ENDODONTICS") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ENDODONTICS$n)
sd(num_ENDODONTICS$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ORAL_MAXILLOFACIAL_SURGERY <- unique_claims %>%
    filter(FY=="2018", CDT_category=="ORAL & MAXILLOFACIAL SURGERY") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ORAL_MAXILLOFACIAL_SURGERY$n)
sd(num_ORAL_MAXILLOFACIAL_SURGERY$n)

#number of ORAL & MAXILLOFACIAL SURGERY services
num_ADJUNCTIVE_GENERAL_SERVICES <- unique_claims %>%
    filter(FY=="2018", CDT_category=="ADJUNCTIVE GENERAL SERVICES") %>%
    group_by(SRECIP) %>%
    count()
mean(num_ADJUNCTIVE_GENERAL_SERVICES$n)
sd(num_ADJUNCTIVE_GENERAL_SERVICES$n)

#age
mean(patient_level_2018$Overall_Age_at_earliest_enrollment)
sd(patient_level_2018$Overall_Age_at_earliest_enrollment)

#age category
table(patient_level_2018$age_cat_eligibility)
round(prop.table(table(patient_level_2018$age_cat_eligibility)), 3)

#race
table(patient_level_2018$Overall_Race)
round(prop.table(table(patient_level_2018$Overall_Race)), 3)

#citizenship
table(patient_level_2018$Overall_Citizen)
round(prop.table(table(patient_level_2018$Overall_Citizen)), 3)

#hpsa
table(patient_level_2018$HPSA_status)
round(prop.table(table(patient_level_2018$HPSA_status)), 3)

#region
table(patient_level_2018$Overall_Region)
round(prop.table(table(patient_level_2018$Overall_Region)), 3)

#hpd
table(patient_level_2018$HEALTH_PLANNING_DISTRICT)
round(prop.table(table(patient_level_2018$HEALTH_PLANNING_DISTRICT)), 3)

#hpr
table(patient_level_2018$HEALTH_PLANNING_REGION)
round(prop.table(table(patient_level_2018$HEALTH_PLANNING_REGION)), 3)

#CDT category
##PREVENTIVE
patient_level_2018$PREVENTIVE <- as.vector(sapply(patient_level_2018$SRECIP, function(x){ifelse("PREVENTIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2018$PREVENTIVE)
prop.table(table(patient_level_2018$PREVENTIVE))

##DIAGNOSTIC
patient_level_2018$DIAGNOSTIC <- as.vector(sapply(patient_level_2018$SRECIP, function(x){ifelse("DIAGNOSTIC" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2018$DIAGNOSTIC)
prop.table(table(patient_level_2018$DIAGNOSTIC))

##RESTORATIVE
patient_level_2018$RESTORATIVE <- as.vector(sapply(patient_level_2018$SRECIP, function(x){ifelse("RESTORATIVE" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2018$RESTORATIVE)
prop.table(table(patient_level_2018$RESTORATIVE))

##PERIODONTICS
patient_level_2018$PERIODONTICS <- as.vector(sapply(patient_level_2018$SRECIP, function(x){ifelse("PERIODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2018$PERIODONTICS)
prop.table(table(patient_level_2018$PERIODONTICS))

##ENDODONTICS
patient_level_2018$ENDODONTICS <- as.vector(sapply(patient_level_2018$SRECIP, function(x){ifelse("ENDODONTICS" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2018$ENDODONTICS)
prop.table(table(patient_level_2018$ENDODONTICS))

##ORAL & MAXILLOFACIAL SURGERY
patient_level_2018$ORAL_and_MAXILLOFACIAL_SURGERY <- as.vector(sapply(patient_level_2018$SRECIP, function(x){ifelse("ORAL & MAXILLOFACIAL SURGERY" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2018$ORAL_and_MAXILLOFACIAL_SURGERY)
prop.table(table(patient_level_2018$ORAL_and_MAXILLOFACIAL_SURGERY))

##OTHER
patient_level_2018$OTHER <- as.vector(sapply(patient_level_2018$SRECIP, function(x){ifelse("OTHER" %in% unique_claims$CDT_category[which(unique_claims$SRECIP==x)], 1, 0)}))
table(patient_level_2018$OTHER)
prop.table(table(patient_level_2018$OTHER))
```

# Making table

```{r}
cbind.data.frame( #all years
				   AY=rbind(nrow(patient_level), 
				   paste0(round(mean(num_claims$n),1), " ", "(", round(sd(num_claims$n),1), ")"),
				   paste0(round(mean(num_visits$n),1), " ", "(", round(sd(num_visits$n),1), ")"),
				   paste0(round(mean(patient_level$Overall_Age_at_earliest_enrollment),1), " ", "(", round(sd(patient_level$Overall_Age_at_earliest_enrollment),1), ")"),
				   "",
				   t(t(paste0(table(patient_level$age_cat_eligibility), " ", "(",round(prop.table(table(patient_level$age_cat_eligibility)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$Overall_Race), " ", "(",round(prop.table(table(patient_level$Overall_Race)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$Overall_Citizen), " ", "(",round(prop.table(table(patient_level$Overall_Citizen)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$HPSA_status), " ", "(",round(prop.table(table(patient_level$HPSA_status)), 3)*100, ")"))),
				   "",
				   paste0(round(mean(patient_level$months_enrolled),1), " ", "(", round(sd(patient_level$months_enrolled),1), ")"),
				   "",
				   t(t(paste0(table(patient_level$months_enrolled_cat), " ", "(",round(prop.table(table(patient_level$months_enrolled_cat)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$Overall_Region), " ", "(",round(prop.table(table(patient_level$Overall_Region)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$HEALTH_PLANNING_DISTRICT), " ", "(",round(prop.table(table(patient_level$HEALTH_PLANNING_DISTRICT)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$HEALTH_PLANNING_REGION), " ", "(",round(prop.table(table(patient_level$HEALTH_PLANNING_REGION)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$PREVENTIVE), " ", "(",round(prop.table(table(patient_level$PREVENTIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$DIAGNOSTIC), " ", "(",round(prop.table(table(patient_level$DIAGNOSTIC)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$RESTORATIVE), " ", "(",round(prop.table(table(patient_level$RESTORATIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$PERIODONTICS), " ", "(",round(prop.table(table(patient_level$PERIODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$ENDODONTICS), " ", "(",round(prop.table(table(patient_level$ENDODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$ORAL_and_MAXILLOFACIAL_SURGERY), " ", "(",round(prop.table(table(patient_level$ORAL_and_MAXILLOFACIAL_SURGERY)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level$OTHER), " ", "(",round(prop.table(table(patient_level$OTHER)), 3)*100, ")")))),
				   
				  #2015
				   FY2015=rbind(nrow(patient_level_2015), 
				   paste0(round(mean(num_claims_2015$n),1), " ", "(", round(sd(num_claims_2015$n),1), ")"),
				   paste0(round(mean(num_visits_2015$n),1), " ", "(", round(sd(num_visits_2015$n),1), ")"),
				   paste0(round(mean(patient_level_2015$Overall_Age_at_earliest_enrollment),1), " ", "(", round(sd(patient_level_2015$Overall_Age_at_earliest_enrollment),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2015$age_cat_eligibility), " ", "(",round(prop.table(table(patient_level_2015$age_cat_eligibility)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$Overall_Race), " ", "(",round(prop.table(table(patient_level_2015$Overall_Race)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$Overall_Citizen), " ", "(",round(prop.table(table(patient_level_2015$Overall_Citizen)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$HPSA_status), " ", "(",round(prop.table(table(patient_level_2015$HPSA_status)), 3)*100, ")"))),
				   "",
				   paste0(round(mean(patient_level_2015$months_enrolled),1), " ", "(", round(sd(patient_level_2015$months_enrolled),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2015$months_enrolled_cat), " ", "(",round(prop.table(table(patient_level_2015$months_enrolled_cat)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$Overall_Region), " ", "(",round(prop.table(table(patient_level_2015$Overall_Region)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$HEALTH_PLANNING_DISTRICT), " ", "(",round(prop.table(table(patient_level_2015$HEALTH_PLANNING_DISTRICT)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$HEALTH_PLANNING_REGION), " ", "(",round(prop.table(table(patient_level_2015$HEALTH_PLANNING_REGION)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$PREVENTIVE), " ", "(",round(prop.table(table(patient_level_2015$PREVENTIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$DIAGNOSTIC), " ", "(",round(prop.table(table(patient_level_2015$DIAGNOSTIC)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$RESTORATIVE), " ", "(",round(prop.table(table(patient_level_2015$RESTORATIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$PERIODONTICS), " ", "(",round(prop.table(table(patient_level_2015$PERIODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$ENDODONTICS), " ", "(",round(prop.table(table(patient_level_2015$ENDODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$ORAL_and_MAXILLOFACIAL_SURGERY), " ", "(",round(prop.table(table(patient_level_2015$ORAL_and_MAXILLOFACIAL_SURGERY)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2015$OTHER), " ", "(",round(prop.table(table(patient_level_2015$OTHER)), 3)*100, ")")))),
				   
				  #2016
				   FY2016=rbind(nrow(patient_level_2016), 
				   paste0(round(mean(num_claims_2016$n),1), " ", "(", round(sd(num_claims_2016$n),1), ")"),
				   paste0(round(mean(num_visits_2016$n),1), " ", "(", round(sd(num_visits_2016$n),1), ")"),
				   paste0(round(mean(patient_level_2016$Overall_Age_at_earliest_enrollment),1), " ", "(", round(sd(patient_level_2016$Overall_Age_at_earliest_enrollment),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2016$age_cat_eligibility), " ", "(",round(prop.table(table(patient_level_2016$age_cat_eligibility)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$Overall_Race), " ", "(",round(prop.table(table(patient_level_2016$Overall_Race)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$Overall_Citizen), " ", "(",round(prop.table(table(patient_level_2016$Overall_Citizen)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$HPSA_status), " ", "(",round(prop.table(table(patient_level_2016$HPSA_status)), 3)*100, ")"))),
				   "",
				   paste0(round(mean(patient_level_2016$months_enrolled),1), " ", "(", round(sd(patient_level_2016$months_enrolled),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2016$months_enrolled_cat), " ", "(",round(prop.table(table(patient_level_2016$months_enrolled_cat)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$Overall_Region), " ", "(",round(prop.table(table(patient_level_2016$Overall_Region)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$HEALTH_PLANNING_DISTRICT), " ", "(",round(prop.table(table(patient_level_2016$HEALTH_PLANNING_DISTRICT)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$HEALTH_PLANNING_REGION), " ", "(",round(prop.table(table(patient_level_2016$HEALTH_PLANNING_REGION)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$PREVENTIVE), " ", "(",round(prop.table(table(patient_level_2016$PREVENTIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$DIAGNOSTIC), " ", "(",round(prop.table(table(patient_level_2016$DIAGNOSTIC)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$RESTORATIVE), " ", "(",round(prop.table(table(patient_level_2016$RESTORATIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$PERIODONTICS), " ", "(",round(prop.table(table(patient_level_2016$PERIODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$ENDODONTICS), " ", "(",round(prop.table(table(patient_level_2016$ENDODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$ORAL_and_MAXILLOFACIAL_SURGERY), " ", "(",round(prop.table(table(patient_level_2016$ORAL_and_MAXILLOFACIAL_SURGERY)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2016$OTHER), " ", "(",round(prop.table(table(patient_level_2016$OTHER)), 3)*100, ")")))),
				   
				  #2017
				   FY2017=rbind(nrow(patient_level_2017), 
				   paste0(round(mean(num_claims_2017$n),1), " ", "(", round(sd(num_claims_2017$n),1), ")"),
				   paste0(round(mean(num_visits_2017$n),1), " ", "(", round(sd(num_visits_2017$n),1), ")"),
				   paste0(round(mean(patient_level_2017$Overall_Age_at_earliest_enrollment),1), " ", "(", round(sd(patient_level_2017$Overall_Age_at_earliest_enrollment),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2017$age_cat_eligibility), " ", "(",round(prop.table(table(patient_level_2017$age_cat_eligibility)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$Overall_Race), " ", "(",round(prop.table(table(patient_level_2017$Overall_Race)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$Overall_Citizen), " ", "(",round(prop.table(table(patient_level_2017$Overall_Citizen)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$HPSA_status), " ", "(",round(prop.table(table(patient_level_2017$HPSA_status)), 3)*100, ")"))),
				   "",
				   paste0(round(mean(patient_level_2017$months_enrolled),1), " ", "(", round(sd(patient_level_2017$months_enrolled),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2017$months_enrolled_cat), " ", "(",round(prop.table(table(patient_level_2017$months_enrolled_cat)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$Overall_Region), " ", "(",round(prop.table(table(patient_level_2017$Overall_Region)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$HEALTH_PLANNING_DISTRICT), " ", "(",round(prop.table(table(patient_level_2017$HEALTH_PLANNING_DISTRICT)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$HEALTH_PLANNING_REGION), " ", "(",round(prop.table(table(patient_level_2017$HEALTH_PLANNING_REGION)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$PREVENTIVE), " ", "(",round(prop.table(table(patient_level_2017$PREVENTIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$DIAGNOSTIC), " ", "(",round(prop.table(table(patient_level_2017$DIAGNOSTIC)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$RESTORATIVE), " ", "(",round(prop.table(table(patient_level_2017$RESTORATIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$PERIODONTICS), " ", "(",round(prop.table(table(patient_level_2017$PERIODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$ENDODONTICS), " ", "(",round(prop.table(table(patient_level_2017$ENDODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$ORAL_and_MAXILLOFACIAL_SURGERY), " ", "(",round(prop.table(table(patient_level_2017$ORAL_and_MAXILLOFACIAL_SURGERY)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2017$OTHER), " ", "(",round(prop.table(table(patient_level_2017$OTHER)), 3)*100, ")")))),
				   
				  #2018
				   FY2018=rbind(nrow(patient_level_2018), 
				   paste0(round(mean(num_claims_2018$n),1), " ", "(", round(sd(num_claims_2018$n),1), ")"),
				   paste0(round(mean(num_visits_2018$n),1), " ", "(", round(sd(num_visits_2018$n),1), ")"),
				   paste0(round(mean(patient_level_2018$Overall_Age_at_earliest_enrollment),1), " ", "(", round(sd(patient_level_2018$Overall_Age_at_earliest_enrollment),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2018$age_cat_eligibility), " ", "(",round(prop.table(table(patient_level_2018$age_cat_eligibility)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$Overall_Race), " ", "(",round(prop.table(table(patient_level_2018$Overall_Race)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$Overall_Citizen), " ", "(",round(prop.table(table(patient_level_2018$Overall_Citizen)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$HPSA_status), " ", "(",round(prop.table(table(patient_level_2018$HPSA_status)), 3)*100, ")"))),
				   "",
				   paste0(round(mean(patient_level_2018$months_enrolled),1), " ", "(", round(sd(patient_level_2018$months_enrolled),1), ")"),
				   "",
				   t(t(paste0(table(patient_level_2018$months_enrolled_cat), " ", "(",round(prop.table(table(patient_level_2018$months_enrolled_cat)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$Overall_Region), " ", "(",round(prop.table(table(patient_level_2018$Overall_Region)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$HEALTH_PLANNING_DISTRICT), " ", "(",round(prop.table(table(patient_level_2018$HEALTH_PLANNING_DISTRICT)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$HEALTH_PLANNING_REGION), " ", "(",round(prop.table(table(patient_level_2018$HEALTH_PLANNING_REGION)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$PREVENTIVE), " ", "(",round(prop.table(table(patient_level_2018$PREVENTIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$DIAGNOSTIC), " ", "(",round(prop.table(table(patient_level_2018$DIAGNOSTIC)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$RESTORATIVE), " ", "(",round(prop.table(table(patient_level_2018$RESTORATIVE)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$PERIODONTICS), " ", "(",round(prop.table(table(patient_level_2018$PERIODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$ENDODONTICS), " ", "(",round(prop.table(table(patient_level_2018$ENDODONTICS)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$ORAL_and_MAXILLOFACIAL_SURGERY), " ", "(",round(prop.table(table(patient_level_2018$ORAL_and_MAXILLOFACIAL_SURGERY)), 3)*100, ")"))),
				   "",
				   t(t(paste0(table(patient_level_2018$OTHER), " ", "(",round(prop.table(table(patient_level_2018$OTHER)), 3)*100, ")"))))
				 )
```

# Plotting

```{r}
Year <- c(rep("2015", 7),
          rep("2016", 7),
          rep("2017", 7),
          rep("2018", 7))
Claim_Type <- rep(c("Preventative",
                    "Diagnostic",
                    "Restorative",
                    "Periodontics",
                    "Endodontics",
                    "Oral & Maxillofacial Surgery",
                    "Other"), 4)
Count <- c(table(patient_level_2015$PREVENTIVE)[2],
           table(patient_level_2015$DIAGNOSTIC)[2],
           table(patient_level_2015$RESTORATIVE)[2],
           table(patient_level_2015$PERIODONTICS)[2],
           table(patient_level_2015$ENDODONTICS)[2],
           table(patient_level_2015$ORAL_and_MAXILLOFACIAL_SURGERY)[2],
           table(patient_level_2015$OTHER)[2],
           table(patient_level_2016$PREVENTIVE)[2],
           table(patient_level_2016$DIAGNOSTIC)[2],
           table(patient_level_2016$RESTORATIVE)[2],
           table(patient_level_2016$PERIODONTICS)[2],
           table(patient_level_2016$ENDODONTICS)[2],
           table(patient_level_2016$ORAL_and_MAXILLOFACIAL_SURGERY)[2],
           table(patient_level_2016$OTHER)[2],
           table(patient_level_2017$PREVENTIVE)[2],
           table(patient_level_2017$DIAGNOSTIC)[2],
           table(patient_level_2017$RESTORATIVE)[2],
           table(patient_level_2017$PERIODONTICS)[2],
           table(patient_level_2017$ENDODONTICS)[2],
           table(patient_level_2017$ORAL_and_MAXILLOFACIAL_SURGERY)[2],
           table(patient_level_2017$OTHER)[2],
           table(patient_level_2018$PREVENTIVE)[2],
           table(patient_level_2018$DIAGNOSTIC)[2],
           table(patient_level_2018$RESTORATIVE)[2],
           table(patient_level_2018$PERIODONTICS)[2],
           table(patient_level_2018$ENDODONTICS)[2],
           table(patient_level_2018$ORAL_and_MAXILLOFACIAL_SURGERY)[2],
           table(patient_level_2018$OTHER)[2])

data <- cbind.data.frame(Year, Claim_Type, Count)
data$Claim_Type <- factor(data$Claim_Type, levels=c("Preventative",
                                                       "Diagnostic",
                                                       "Restorative",
                                                       "Periodontics",
                                                       "Endodontics",
                                                       "Oral & Maxillofacial Surgery",
                                                       "Other"))

ggplot(data, aes(fill=Claim_Type, y=Count, x=Year)) + 
  geom_bar(position="dodge", stat="identity") +
  ylab("Counts of Services") +
  scale_fill_discrete(name="Claim Type")+
  theme_bw() +
  #coord_flip() +
  theme(axis.text.x = element_text(size=15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        strip.text.x = element_text(size = 15),
        panel.spacing = unit(2, "lines"),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20))
  
spread(data, Year, Count) 
```

